apiVersion: policies.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-trustedcontainer
  namespace: default
  annotations:
    policies.open-cluster-management.io/standards: NIST-CSF
    policies.open-cluster-management.io/categories: PR.PT Protective Technology
    policies.open-cluster-management.io/controls: PR.PT-3 Least Functionality
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policies.ibm.com/v1alpha1
        kind: TrustedContainerPolicy
        metadata:
          name: example-trustedcontainerpolicy
        spec:
          severity: low
          namespaceSelector:
            include: ["default"]
            exclude: ["kube-system"]
          remediationAction: inform
          imageRegistry: quay.io
---
apiVersion: policies.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-trustedcontainer
  namespace: default
placementRef:
  name: placement-policy-trustedcontainer
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-trustedcontainer
  kind: Policy
  apiGroup: policies.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-trustedcontainer
  namespace: default
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["ironman"]}

