kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trusted-container-policy-controller
subjects:
- kind: ServiceAccount
  name: trusted-container-policy-controller
  namespace: multicluster-endpoint
roleRef:
  kind: ClusterRole
  name: trusted-container-policy-controller
  apiGroup: rbac.authorization.k8s.io
